import { getSupabaseClient } from './supabaseClient';

/**
 * Represents a single page visit record.
 *
 * @property id - Auto-generated unique identifier (from database)
 * @property path - URL path that was visited
 * @property visited_at - ISO 8601 timestamp of the visit (auto-generated by database)
 * @property user_agent - Browser user agent string
 * @property referrer - Referring URL (if any)
 * @property session_id - Unique session identifier for grouping visits
 */
export interface PageVisit {
  id?: number;
  path: string;
  visited_at?: string;
  user_agent?: string;
  referrer?: string;
  session_id?: string;
}

/**
 * Aggregated visit statistics for a specific path.
 *
 * @property total_visits - Total number of visits to this path
 * @property unique_sessions - Number of unique sessions that visited this path
 * @property last_visit - ISO 8601 timestamp of the most recent visit
 * @property first_visit - ISO 8601 timestamp of the first visit
 */
export interface VisitStats {
  total_visits: number;
  unique_sessions: number;
  last_visit: string;
  first_visit: string;
}

/**
 * Generates or retrieves a unique session ID from localStorage.
 * Creates a UUID v4 format identifier if one doesn't exist.
 * The session ID persists across page reloads within the same browser.
 *
 * @returns Unique session identifier string
 *
 * @internal
 */
function getSessionId(): string {
  const SESSION_KEY = 'adamowo_session_id';
  let sessionId = localStorage.getItem(SESSION_KEY);

  if (!sessionId) {
    // Generate a simple UUID v4
    sessionId = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
    localStorage.setItem(SESSION_KEY, sessionId);
  }

  return sessionId;
}

/**
 * Tracks a page visit to the analytics database.
 * Records the path, user agent, referrer, and session ID.
 * Silently fails if Supabase is not configured.
 *
 * @param path - URL path to track (e.g., '/about', '/episodes')
 * @returns Promise that resolves when tracking is complete
 *
 * @example
 * ```typescript
 * // Track current page
 * await trackPageVisit(window.location.pathname);
 *
 * // Track specific path
 * await trackPageVisit('/studio/adamology');
 * ```
 */
export async function trackPageVisit(path: string): Promise<void> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    console.warn('Analytics: Supabase not configured, skipping page visit tracking');
    return;
  }

  try {
    const visit: PageVisit = {
      path,
      user_agent: navigator.userAgent,
      referrer: document.referrer || null,
      session_id: getSessionId(),
    };

    const { error } = await supabase.from('page_visits').insert([visit]);

    if (error) {
      console.error('Analytics: Error tracking page visit:', error);
    }
  } catch (error) {
    console.error('Analytics: Failed to track page visit:', error);
  }
}

/**
 * Gets the total visit count across all pages.
 * Uses the database RPC function 'get_total_visits'.
 * Returns 0 if Supabase is not configured or on error.
 *
 * @returns Promise resolving to total visit count
 *
 * @example
 * ```typescript
 * const total = await getTotalVisits();
 * console.log(`Total visits: ${total}`);
 * ```
 */
export async function getTotalVisits(): Promise<number> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    console.warn('Analytics: Supabase not configured');
    return 0;
  }

  try {
    const { data, error } = await supabase.rpc('get_total_visits');

    if (error) {
      console.error('Analytics: Error getting total visits:', error);
      return 0;
    }

    return data || 0;
  } catch (error) {
    console.error('Analytics: Failed to get total visits:', error);
    return 0;
  }
}

/**
 * Gets the visit count for a specific path.
 * Uses the database RPC function 'get_visits_by_path'.
 * Returns 0 if Supabase is not configured or on error.
 *
 * @param path - URL path to query (e.g., '/about', '/episodes')
 * @returns Promise resolving to visit count for the specified path
 *
 * @example
 * ```typescript
 * const visits = await getVisitsByPath('/studio/adamology');
 * console.log(`Adamology has ${visits} visits`);
 * ```
 */
export async function getVisitsByPath(path: string): Promise<number> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    console.warn('Analytics: Supabase not configured');
    return 0;
  }

  try {
    const { data, error } = await supabase.rpc('get_visits_by_path', { p_path: path });

    if (error) {
      console.error('Analytics: Error getting visits by path:', error);
      return 0;
    }

    return data || 0;
  } catch (error) {
    console.error('Analytics: Failed to get visits by path:', error);
    return 0;
  }
}

/**
 * Gets detailed visit statistics for a specific path.
 * Queries the 'page_visit_stats' database view.
 * Returns null if Supabase is not configured, path not found, or on error.
 *
 * @param path - URL path to query statistics for
 * @returns Promise resolving to visit statistics, or null if unavailable
 *
 * @example
 * ```typescript
 * const stats = await getVisitStats('/episodes');
 * if (stats) {
 *   console.log(`Total: ${stats.total_visits}, Unique: ${stats.unique_sessions}`);
 *   console.log(`First visit: ${stats.first_visit}`);
 * }
 * ```
 */
export async function getVisitStats(path: string): Promise<VisitStats | null> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    console.warn('Analytics: Supabase not configured');
    return null;
  }

  try {
    const { data, error } = await supabase
      .from('page_visit_stats')
      .select('*')
      .eq('path', path)
      .single();

    if (error) {
      console.error('Analytics: Error getting visit stats:', error);
      return null;
    }

    return data as VisitStats;
  } catch (error) {
    console.error('Analytics: Failed to get visit stats:', error);
    return null;
  }
}

/**
 * Gets visit statistics for all paths.
 * Queries the 'page_visit_stats' database view and returns results keyed by path.
 * Returns empty object if Supabase is not configured or on error.
 *
 * @returns Promise resolving to object mapping paths to their visit statistics
 *
 * @example
 * ```typescript
 * const allStats = await getAllVisitStats();
 * Object.entries(allStats).forEach(([path, stats]) => {
 *   console.log(`${path}: ${stats.total_visits} visits`);
 * });
 * ```
 */
export async function getAllVisitStats(): Promise<Record<string, VisitStats>> {
  const supabase = getSupabaseClient();

  if (!supabase) {
    console.warn('Analytics: Supabase not configured');
    return {};
  }

  try {
    const { data, error } = await supabase.from('page_visit_stats').select('*');

    if (error) {
      console.error('Analytics: Error getting all visit stats:', error);
      return {};
    }

    // Convert array to record keyed by path
    const stats: Record<string, VisitStats> = {};
    if (data) {
      data.forEach((stat: VisitStats & { path: string }) => {
        stats[stat.path] = stat;
      });
    }

    return stats;
  } catch (error) {
    console.error('Analytics: Failed to get all visit stats:', error);
    return {};
  }
}
